name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'meow-meow'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Send build files to VPS
        run: rsync -avz -r --delete --include="main.py" --exclude="*" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DIRECTORY_PATH }}

      - name: Send other files to VPS
        run: rsync -avs -r --delete --include="requirements.txt" --include="currentquota.txt" --exclude="*" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DIRECTORY_PATH }}

      - name: Hi ahmood
        run: rsync -avs -r --delete --include="commands/" --include="commands/**" --exclude="*" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DIRECTORY_PATH }}

      - name: Restart PM2 Process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.profile
            cd ${{ secrets.SSH_DIRECTORY_PATH }}
            pm2 restart Marketplace-Bot
