name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'meow-meow'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Send files to VPS
        run: rsync -avz -r --delete --exclude="quotaDB.sqlite" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DIRECTORY_PATH }}

      - name: Restart PM2 Process
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIRECTORY_PATH }}; export NVM_DIR=~/.nvm; source ~/.nvm/nvm.sh; pm2 restart MPQuotaBot;"
